### ISSUE TITLE
SecurityAdvisory does "work" in the constructor

### ISSUE THREAD

**Issue by kbond** [laminas/laminas-diagnostics#28]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.0

#### Summary

https://github.com/laminas/laminas-diagnostics/pull/16 added code does work in `SecurityAdvisory::__construct()` that causes temporary files to be created. Related: https://github.com/liip/LiipMonitorBundle/issues/261.

Ping @paras-malhotra.

**Comment by Ocramius** [comment]
Hey @kbond, the code in #16 does not include added code that generates temporary files: can you link to a specific code fragment, please?

**Comment by lostfocus** [comment]
Hi, I was the original reporter in https://github.com/liip/LiipMonitorBundle/issues/261 - the problem is happening here: https://github.com/laminas/laminas-diagnostics/blob/1557e3f173fd00291d286b3ea1b98454c21b08d4/src/Check/SecurityAdvisory.php#L60 
The function call within the constructor triggers a download of https://codeload.github.com/FriendsOfPHP/security-advisories/zip/master in the Enlightn Security Checker. (https://github.com/enlightn/security-checker/blob/main/src/AdvisoryFetcher.php)

**Comment by Ocramius** [comment]
I see - indeed, that should be moved to the body of the check.

Can you adjust that through a patch perhaps?

**Comment by Ocramius** [comment]
This was handled in #29
