### ISSUE TITLE
Casting question

### ISSUE THREAD

**Issue by cronlabspl** [laminas/laminas-diagnostics#35]
https://github.com/laminas/laminas-diagnostics/blob/4f6c493e9d6fa57f29d32671a4a86e841afd9428/src/Check/AbstractMemoryCheck.php#L61

why `int` is casted to `int` here?

**Comment by Ocramius** [comment]
The problem here is that in this section:

https://github.com/laminas/laminas-diagnostics/blob/4f6c493e9d6fa57f29d32671a4a86e841afd9428/src/Check/AbstractMemoryCheck.php#L30-L47

`$warningThreshold` could be `100.00` or `'100'`.

These are remnants of how we used to code before PHP 7.0 introduced strict scalar types: if this was coded nowadays, the scalar type would be part of the function signature, without much checking at runtime.
